apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: movies-service
  name: movies-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: movies-service
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgres://postgres:postgres@movies-db:4004/movies
        - name: NEW_RELIC_APP_NAME
          value: movies-service
        - name: NEW_RELIC_LICENSE_KEY
          value: cec283018fe0214f68b46ecc1223ffc43818d5ca
        - name: TOKEN_SECRET
          value: Zed-Is-Dead-Baby-Zed-Is-Dead
        - name: USERS_SERVICE_URL
          value: localhost:3002
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: victormileto/movies-service:latest
        name: movies-service
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
